### ISSUE TITLE
cargo build error

### ISSUE THREAD

**Issue by pallavikhtri25** [radu-matei/wasi-tensorflow-inference#1]
![image](https://user-images.githubusercontent.com/72016802/99962678-9d392d80-2db6-11eb-9c9b-e104dca0ed2f.png)

**Comment by radu-matei** [comment]
The documentation mentions that you need to have `wasm-opt` configured in your path in order to successfully build - you can download it from the Binaryen releases here - https://github.com/WebAssembly/binaryen/releases

However, if you only want to run the project, you can comment that particular line, as there is already a compiled module in the `model/` directory.

**Comment by radu-matei** [comment]
Closing, as there doesn't seem to be an actionable item here.

Feel free to reopen if you feel the build process should change!
